- hosts: web
  become: true
  tasks:
    - name: Installs apache web server
      apt:
        pkg: "{{item}}"
        state: latest
        update_cache: true
      with_items:
        - apache2
        - libapache2-mod-php
        - git
    
    - name: Push default virtual host configuration
      copy:
        src: files/awesome-app
        dest: /etc/apache2/sites-available/awesome-app
        mode: 0640

    - name: Disable the default virtualhost
      file:
        dest: /etc/apache2/sites-enabled/default
        state: absent
      notify:
        - restart apache
 
    - name: Disable the default ssl virtualhost
      file:
        dest: /etc/apache2/sites-enabled/default-ssl
        state: absent
      notify:
        - restart apache

    - name: Activates our virtualhost
      file:
        src: /etc/apache2/sites-available/awesome-app
        dest: /etc/apache2/sites-enabled/awesome-app
        state: link
      notify:
        - restart apache
    - name: deploy app
      git:
        repo: https://github.com/jwkidd3/theapp
        dest: /var/www/awesome-app 
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
