---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a resource
      azure_rm_resourcegroup:
        name: table5jl_ansibletest
        location: eastus2
        tags:
          testing: testing
          delete: never
