- name: Create  VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: table5jl_vmrg
      location: eastus2
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: table5jl_vmrg
      name: table5jlvnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: table5jl_vmrg
      name: table5jlsubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: table5jlvnet
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: table5jl_vmrg
      allocation_method: Static
      name: table5jlpublicip
    register: output_ip_address
  - name: Output public IP 
    debug:
      msg: "Public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: table5jl_vmrg
      name: table5jlnsg1
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: table5jl_vmrg
      name: table5jlnic
      virtual_network: table5jlvnet
      subnet: table5jlsubnet
      public_ip_name: table5jlpublicip
      security_group: myNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: table5jl_vmrg
      name: table5jlnode1vm
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: |
            {{ lookup('file','/home/azureops/.ssh/id_rsa.pub') }}
      network_interfaces: table5jlnic
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-lts'
        version: latest
  - name: Install Apache
    apt:
      pkg: apache2
      state: present
      update_cache: true
