- name: Create  VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: table5jl_vmrg
      location: eastus2
      state: absent
      force: yes
